server:
  port: 8012
  servlet:
    context-path: /business
spring:
  application:
    name: busines
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        url: jdbc:mysql://192.168.1.10:3306/lzm_qrc_access?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: lzmdb
        password: lzm123
        initial-size: 1
        max-active: 20
        min-idle: 5
        max-wait: 6000
        pool-prepared-statements: false
        max-open-prepared-statements: 100
        validation-query: SELECT 1 FROM DUAL

mybatis-plus:
  type-aliases-package: cn.zzstc.dastabase.entity
  mapper-locations: classpath*:cn/zzstc/dastabase/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.55:8011/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 40
    lease-renewal-interval-in-seconds: 40
    hostname: business



